#!/usr/bin/env python3
"""Regenerate docs/images/star-history.svg from the GitHub stargazer API.

Standard-library only, so the nightly workflow needs no package install.
The output is deterministic: the same stargazer timeline always produces
the same SVG, so the workflow only commits when the timeline changed.

The token is read from GITHUB_TOKEN / STAR_TOKEN. It is used only for the
API request and never appears in the chart or in any repository file.
"""

import argparse
import datetime as dt
import html
import json
import os
import sys
import urllib.error
import urllib.request

API = "https://api.github.com"

WIDTH, HEIGHT = 860, 340
MARGIN_L, MARGIN_R, MARGIN_T, MARGIN_B = 48, 18, 18, 36
FONT = '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif'
INK = "#1f2328"
GRID = "#eaeef2"
AXIS = "#d0d7de"
SERIES = "#0969da"
FILL = "#ddf4ff"

STEPS = (1, 2, 5, 10, 20, 25, 50, 100, 200, 250, 500,
         1000, 2000, 2500, 5000, 10000, 25000, 50000, 100000)


def fetch_stargazer_dates(repo, token):
    """Return the ISO timestamp of every star, in API order."""
    dates = []
    page = 1
    while True:
        url = f"{API}/repos/{repo}/stargazers?per_page=100&page={page}"
        req = urllib.request.Request(url, headers={
            "Accept": "application/vnd.github.star+json",
            "Authorization": f"Bearer {token}",
            "User-Agent": "star-history-chart",
        })
        with urllib.request.urlopen(req, timeout=30) as resp:
            batch = json.load(resp)
        if not batch:
            break
        for item in batch:
            stamp = item.get("starred_at")
            if stamp:
                dates.append(dt.datetime.fromisoformat(stamp.replace("Z", "+00:00")))
        if len(batch) < 100:
            break
        page += 1
    return dates


def daily_series(dates):
    """Cumulative star count per day, starting at zero the day before the first star."""
    if not dates:
        return []
    by_day = {}
    for when in dates:
        by_day[when.date()] = by_day.get(when.date(), 0) + 1
    first, last = min(by_day), max(by_day)
    points = [(first - dt.timedelta(days=1), 0)]
    running = 0
    day = first
    while day <= last:
        running += by_day.get(day, 0)
        points.append((day, running))
        day += dt.timedelta(days=1)
    return points


def fmt_count(value):
    if value >= 1000:
        return f"{value / 1000:.1f}".rstrip("0").rstrip(".") + "k"
    return str(value)


def x_ticks(first, last):
    """Return (dates, label format) for the x axis."""
    span = (last - first).days
    if span <= 45:
        step = max(1, -(-span // 8))
        return [first + dt.timedelta(days=i * step) for i in range(span // step + 1)], "%m-%d"
    if span <= 730:
        ticks, y, m = [], first.year, first.month
        while (y, m) <= (last.year, last.month):
            ticks.append(dt.date(y, m, 1))
            m += 1
            if m == 13:
                m, y = 1, y + 1
        step = max(1, -(-len(ticks) // 8))
        return ticks[::step], "%Y-%m"
    ticks, y = [], first.year
    while y <= last.year:
        ticks.append(dt.date(y, 1, 1))
        y += 1
    return ticks, "%Y"


def build_svg(points):
    lines = []
    add = lines.append

    x0, x1 = MARGIN_L, WIDTH - MARGIN_R
    y0, y1 = MARGIN_T, HEIGHT - MARGIN_B
    plot_w, plot_h = x1 - x0, y1 - y0

    max_count = max(c for _, c in points) if points else 0
    step = next((s for s in STEPS if s >= max_count / 4), 100000)
    ymax = -(-max_count // step) * step if max_count else 10
    y_ticks = list(range(0, ymax + 1, step))

    span_days = 6
    if points:
        span_days = max(span_days, (points[-1][0] - points[0][0]).days + 6)
    t0 = (points[0][0] - dt.timedelta(days=3)) if points else dt.date.today()
    t1 = (points[-1][0] + dt.timedelta(days=3)) if points else t0 + dt.timedelta(days=6)

    def px(date):
        return x0 + (date - t0).days / (t1 - t0).days * plot_w

    def py(count):
        return y0 + (1 - count / ymax) * plot_h

    add(f'<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" '
        f'viewBox="0 0 {WIDTH} {HEIGHT}" font-family="{html.escape(FONT)}">')
    add("<!-- regenerated by scripts/star-history.py; see .github/workflows/star-chart.yml -->")
    add(f'<rect width="{WIDTH}" height="{HEIGHT}" fill="#ffffff"/>')

    for tick in y_ticks:
        y = py(tick)
        add(f'<line x1="{x0}" y1="{y:.1f}" x2="{x1}" y2="{y:.1f}" stroke="{GRID}"/>')
        add(f'<text x="{x0 - 8}" y="{y + 4:.1f}" font-size="11" fill="{INK}" '
            f'text-anchor="end">{html.escape(fmt_count(tick))}</text>')

    tick_dates, tick_fmt = x_ticks(t0, t1) if points else ([], "%m-%d")
    for when in tick_dates:
        x = px(when)
        add(f'<line x1="{x:.1f}" y1="{y0}" x2="{x:.1f}" y2="{y1}" stroke="{GRID}"/>')
        add(f'<text x="{x:.1f}" y="{y1 + 18}" font-size="11" fill="{INK}" '
            f'text-anchor="middle">{html.escape(when.strftime(tick_fmt))}</text>')

    add(f'<line x1="{x0}" y1="{y1}" x2="{x1}" y2="{y1}" stroke="{AXIS}"/>')
    add(f'<line x1="{x0}" y1="{y0}" x2="{x0}" y2="{y1}" stroke="{AXIS}"/>')

    if points:
        coords = [(px(d), py(c)) for d, c in points]
        line = " L".join(f"{x:.1f} {y:.1f}" for x, y in coords)
        add(f'<path d="M{x0} {y1} L{line} L{coords[-1][0]:.1f} {y1} Z" fill="{FILL}"/>')
        add(f'<path d="M{line}" fill="none" stroke="{SERIES}" stroke-width="2"/>')
        lx, ly = coords[-1]
        add(f'<circle cx="{lx:.1f}" cy="{ly:.1f}" r="3.5" fill="{SERIES}"/>')
        label = fmt_count(points[-1][1])
        anchor = "end" if lx > x1 - 70 else "start"
        lx_text = lx - 9 if anchor == "end" else lx + 9
        add(f'<text x="{lx_text:.1f}" y="{ly - 6:.1f}" font-size="14" font-weight="600" '
            f'fill="{INK}" text-anchor="{anchor}">{html.escape(label)}</text>')
        add(f'<text x="{lx_text:.1f}" y="{ly + 10:.1f}" font-size="11" fill="{INK}" '
            f'text-anchor="{anchor}">stars</text>')
    else:
        add(f'<text x="{(x0 + x1) / 2:.1f}" y="{(y0 + y1) / 2:.1f}" font-size="13" '
            f'fill="{INK}" text-anchor="middle">No star data yet</text>')

    add("</svg>")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo",
                        default=os.environ.get("GITHUB_REPOSITORY", "smthdagg/wificalling-location-gateway"))
    parser.add_argument("--out", default="docs/images/star-history.svg")
    args = parser.parse_args()

    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("STAR_TOKEN")
    if not token:
        print("GITHUB_TOKEN/STAR_TOKEN is not set", file=sys.stderr)
        return 2
    try:
        dates = fetch_stargazer_dates(args.repo, token)
    except urllib.error.HTTPError as exc:
        body = exc.read().decode(errors="replace")[:300]
        print(f"GitHub API error {exc.code}: {body}", file=sys.stderr)
        return 1
    except (urllib.error.URLError, OSError) as exc:
        print(f"network error: {exc}", file=sys.stderr)
        return 1

    points = daily_series(dates)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(build_svg(points))
    print(f"wrote {args.out}: {len(dates)} stars over {len(points)} days", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
